### ISSUE TITLE
joomla-framework/http version 2.0.0

### ISSUE THREAD

**Issue by zero-24** [joomlagerman/jgerman-bot#2]
Make the usage of the joomla-framework/http package version 2.0 compatible.

The reported issue is:
```
PHP Deprecated:  Non-static method Joomla\Http\HttpFactory::getHttp() should not be called statically in /home/runner/work/jgerman-bot/jgerman-bot/src/NotifyerHelper.php on line 39
PHP Fatal error:  Uncaught Error: Using $this when not in object context in /home/runner/work/jgerman-bot/jgerman-bot/vendor/joomla/http/src/HttpFactory.php:39
Stack trace:
#0 /home/runner/work/jgerman-bot/jgerman-bot/src/NotifyerHelper.php(39): Joomla\Http\HttpFactory::getHttp()
#1 /home/runner/work/jgerman-bot/jgerman-bot/includes/github-base.php(46): joomlagerman\Helper\NotifyerHelper->__construct(Object(Joomla\Registry\Registry))
#2 /home/runner/work/jgerman-bot/jgerman-bot/cli/jgerman-github-bot.php(30): require('/home/runner/wo...')
#3 {main}
  thrown in /home/runner/work/jgerman-bot/jgerman-bot/vendor/joomla/http/src/HttpFactory.php on line 39
```

Thanks @wojsmol for the report.

**Comment by zero-24** [comment]
For now I dont see the need and saddly also dont have time to do such change. Via composer.json we have made sure that 1.3 is installed. Closing
